cpdoi{
	httpBindInterface = "localhost"
	httpBindPort = 8079
	admins = []

	envri = "ICOS"

	envriConfigs{
		ICOS{
			test{
				restEndpoint = "https://api.test.datacite.org/"
				member{
					symbol = "ZHRH.ICOS"
					password = ""
					prefix = "10.23679"
				}
			}

			production{
				restEndpoint = "https://api.datacite.org/"
				member{
					symbol = "SND.ICOS"
					password = ""
					prefix = "10.18160"
				}
			}

			mailing{
				smtpServer: "localhost"
				username: "doi@icos-cp.eu"
				password: ""
				fromAddress: "doi@icos-cp.eu"
				toAddresses: []
			}
			metaHost = "127.0.0.1:9094"
			publicHost = "localhost:8079"
		}

		SITES{
			production{
				restEndpoint = "https://api.datacite.org/"
				member{
					symbol = "SND.SITES"
					password = ""
					prefix = "10.23700"
				}
			}

			mailing{
				smtpServer: "localhost"
				username: "doi@fieldsites.se"
				password: ""
				fromAddress: "doi@fieldsites.se"
				toAddresses: []
			}
			metaHost = "127.0.0.1:9096"
			publicHost = "localhost:8079"
		}
	}

	# Defaults are local-development friendly. Production deployments should override these.
	development = true
	skipCacheInvalidation = true
}
